//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Authentication.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public  class ResponseMessage_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ResponseMessage_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Authentication.Common.Resources.ResponseMessage_en_US", typeof(ResponseMessage_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string RC0001 {
            get {
                return ResourceManager.GetString("RC0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A technical error has occurred!.
        /// </summary>
        internal static string RC0002 {
            get {
                return ResourceManager.GetString("RC0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password. Please check your username and password..
        /// </summary>
        internal static string RC0005 {
            get {
                return ResourceManager.GetString("RC0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not match!.
        /// </summary>
        internal static string RC0006 {
            get {
                return ResourceManager.GetString("RC0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authority information not found!.
        /// </summary>
        internal static string RC0007 {
            get {
                return ResourceManager.GetString("RC0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role information not found!.
        /// </summary>
        internal static string RC0008 {
            get {
                return ResourceManager.GetString("RC0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group information not found!.
        /// </summary>
        internal static string RC0009 {
            get {
                return ResourceManager.GetString("RC0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application verification failed!.
        /// </summary>
        internal static string RC0010 {
            get {
                return ResourceManager.GetString("RC0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Sending Mail..
        /// </summary>
        internal static string RC00100 {
            get {
                return ResourceManager.GetString("RC00100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your old password does not match!.
        /// </summary>
        internal static string RC0011 {
            get {
                return ResourceManager.GetString("RC0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data information is incomplete on request!.
        /// </summary>
        internal static string RC0012 {
            get {
                return ResourceManager.GetString("RC0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was not associated with any application!.
        /// </summary>
        internal static string RC0013 {
            get {
                return ResourceManager.GetString("RC0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration with the same user name is available in the system. Please enter a different username..
        /// </summary>
        internal static string RC0014 {
            get {
                return ResourceManager.GetString("RC0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail address is used!.
        /// </summary>
        internal static string RC0015 {
            get {
                return ResourceManager.GetString("RC0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User registration is not active!.
        /// </summary>
        internal static string RC0016 {
            get {
                return ResourceManager.GetString("RC0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to upload a profile picture!.
        /// </summary>
        internal static string RC0017 {
            get {
                return ResourceManager.GetString("RC0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t repeat group name!.
        /// </summary>
        internal static string RC0018 {
            get {
                return ResourceManager.GetString("RC0018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name can not repeat!.
        /// </summary>
        internal static string RC0019 {
            get {
                return ResourceManager.GetString("RC0019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password length must be at least {0} characters!.
        /// </summary>
        internal static string RC0020 {
            get {
                return ResourceManager.GetString("RC0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password length must be at most {0} characters!.
        /// </summary>
        internal static string RC0021 {
            get {
                return ResourceManager.GetString("RC0021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should only contain numbers!.
        /// </summary>
        internal static string RC0022 {
            get {
                return ResourceManager.GetString("RC0022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain only letters!.
        /// </summary>
        internal static string RC0023 {
            get {
                return ResourceManager.GetString("RC0023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain letters or numbers!.
        /// </summary>
        internal static string RC0024 {
            get {
                return ResourceManager.GetString("RC0024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain numbers, upper case and lower case!.
        /// </summary>
        internal static string RC0025 {
            get {
                return ResourceManager.GetString("RC0025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain numbers, letters and special characters!.
        /// </summary>
        internal static string RC0026 {
            get {
                return ResourceManager.GetString("RC0026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain uppercase, lowercase, numbers or special characters!.
        /// </summary>
        internal static string RC0027 {
            get {
                return ResourceManager.GetString("RC0027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain uppercase, lowercase, numbers and special characters!.
        /// </summary>
        internal static string RC0028 {
            get {
                return ResourceManager.GetString("RC0028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is blocked. You can unblock by calling customer service..
        /// </summary>
        internal static string RC0029 {
            get {
                return ResourceManager.GetString("RC0029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to he new password you entered must be different from your last {0} password, or the change was denied because you changed the last {0} days..
        /// </summary>
        internal static string RC0030 {
            get {
                return ResourceManager.GetString("RC0030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Not Found!.
        /// </summary>
        internal static string RC0031 {
            get {
                return ResourceManager.GetString("RC0031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu name is using..
        /// </summary>
        internal static string RC0032 {
            get {
                return ResourceManager.GetString("RC0032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Expire!.
        /// </summary>
        internal static string RC0033 {
            get {
                return ResourceManager.GetString("RC0033", resourceCulture);
            }
        }
    }
}
